---
- name: Add the app user
  user:
    name: "{{ app_user }}"
    shell: /bin/bash
    group: sudo

- name: Set authorized key for new user
  authorized_key:
    user: "{{ app_user }}"
    state: present
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
