---
- name: Install PostgreSQL
  apt: name={{ item }} update_cache=true state=present
  with_items:
    - libpq-dev
    - pip
    - postgresql
    - postgresql-contrib

- name: Make sure psycopg2 is installed
  pip:
    name: psycopg2
    state: present

- name: Ensure the PostgreSQL service is running
  service: name=postgresql state=started enabled=yes
  become: yes

- name: Ensure database is created
  postgresql_db: name={{ db_name }}
                 encoding='UTF-8'
                 lc_collate='C.UTF-8'
                 lc_ctype='C.UTF-8'
                 template='template0'
                 state=present
  become: yes
  become_user: postgres

- name: Ensure user has access to the database
  postgresql_user: db={{ db_name }}
                   name={{ db_user }}
                   password={{ db_password }}
                   priv=ALL
                   state=present
  become: yes
  become_user: postgres

- name: Ensure user does not have unnecessary privileges
  postgresql_user: name={{ db_user }}
                   role_attr_flags=NOSUPERUSER,NOCREATEDB
                   state=present
  become: yes
  become_user: postgres
