---
- name: Import GPG keys from keyservers
  command: 'gpg2 --batch --keyserver {{ item }} --recv-keys {{ gpg_keys }}'
  changed_when: false
  with_items: '{{ gpg_key_servers }}'
  register: gpg_import
  when: gpg_import is not defined or gpg_import.rc != 0
  ignore_errors: true
  args:
    warn: false

- name: Check import from keyservers
  set_fact: gpg_imported_from={{ item.item }}
  when: "'rc' in item and item.rc == 0"
  with_items: "{{ gpg_import.results }}"

- name: Import GPG keys from rvm.io, if keyservers failed
  shell: 'curl -sSL https://rvm.io/{{ item }} | gpg2 --batch --import -'
  with_items:
    - mpapis.asc
    - pkuczynski.asc
  when: gpg_imported_from is not defined